# Generated by Django 4.1.7 on 2023-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('kind', models.CharField(choices=[('english', '英式红茶'), ('chinese', '中国茶'), ('japanese', '日本茶')], max_length=255, verbose_name='种类')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='推荐商品')),
            ],
        ),
    ]
