# Generated by Django 4.1.7 on 2023-03-26 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 8, 34, 49, 853582, tzinfo=datetime.timezone.utc), verbose_name='data published'),
            preserve_default=False,
        ),
    ]
